name: "Run Gorila Action"
description: "Run a custom action"

inputs:
  action:
    description: "The action to run"
    required: true
  sshkey:
    description: "The ssh key to checkout private actions repo"
    required: true
  ecr-access-key:
    description: 'The access key to manage the ECR to push the image'
    required: true
  ecr-access-key-id:
    description: 'The ID to manage the ECR to push the image'
    required: true
  npm-token:
    description: 'The npm token used to build the app'
    required: false
  environment:
    description: 'The environment to deploy on'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Checkout Actions Repo
      uses: actions/checkout@v3
      with:
        repository: gorilainvest/actions
        ssh-key: ${{ inputs.sshkey }}
        path: ./private_actions
    - name: Run reusable actions
      uses: ./private_actions/
      with:
        action-name: ${{ inputs.action }}
        ecr-access-key: ${{ inputs.ecr-access-key }}
        ecr-access-key-id: ${{ inputs.ecr-access-key-id }}
        npm-token: ${{ inputs.npm-token }}
        environment: ${{ inputs.environment }}
