name: "Run Gorila Action"
description: "Run a custom action"

inputs:
  sshkey:
    description: "The ssh key to checkout private actions repo"
    required: true
  action:
    description: "The action to run"
    required: true
  environment:
    description: 'The environment to deploy on'
    required: false
    # development or production (in future staging)
    default: 'development'
  ecr-access-key:
    description: 'The access key to manage the ECR to push the image'
    required: true
  ecr-access-key-id:
    description: 'The ID to manage the ECR to push the image'
    required: true
  npm-token:
    description: 'The npm token used to build the app'
    required: false
  dockerfile-path:
    description: 'The path to the Dockerfile to build'
    required: false
    default: './Dockerfile'
  dockerfile-context:
    description: 'The context to use when building the Dockerfile'
    required: false
    default: '.'
  aws-access-key-id:
    description: 'The AWS access key ID to use when building the Dockerfile'
    required: false
    default: ''
  aws-access-key-secret:
    description: 'The AWS access key secret to use when building the Dockerfile'
    required: false
    default: ''
  aws-default-region:
    description: 'The AWS default regions to use when building the Dockerfile'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Checkout Actions Repo
      uses: actions/checkout@v3
      with:
        repository: gorilainvest/actions
        ssh-key: ${{ inputs.sshkey }}
        path: ./private_actions
    - name: Run reusable actions
      uses: ./private_actions/
      with:
        action-name: ${{ inputs.action }}
        environment: ${{ inputs.environment }}
        ecr-access-key: ${{ inputs.ecr-access-key }}
        ecr-access-key-id: ${{ inputs.ecr-access-key-id }}
        npm-token: ${{ inputs.npm-token }}
        dockerfile-path: ${{ inputs.dockerfile-path }}
        dockerfile-context: ${{ inputs.dockerfile-context }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-access-key-secret: ${{ inputs.aws-access-key-secret }}
        aws-default-region: ${{ inputs.aws-default-region }}