name: "Run Gorila Action"
description: "Run a custom action"

inputs:
  action:
    description: "The action to run"
    required: true
  ssh-key:
    description: "The ssh key to checkout private actions repo"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Checkout Actions Repo
      uses: actions/checkout@v3
      with:
        repository: gorilainvest/actions
        ssh-key: ${{ github.event.inputs.ssh-key }}
        path: ./private_actions
    - name: Run reusable actions
      uses: ./private_actions/${{ github.event.inputs.action }}
      with:
        username: gorilainvest
