name: "Run Gorila Action"
description: "Run a custom action"
inputs:
  action:
    description: "The action to run"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Checkout Actions Repo
      uses: actions/checkout@v3
      with:
        repository: gorilainvest/actions
        ssh-key: ${{ secrets.ACTIONS_CHECKOUT_SSH }}
        path: ./private_actions
    - name: Run reusable actions
      uses: ./private_actions/${{input.action}}
      with:
        username: gorilainvest